/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    SCanvas: typeof import('./lib/components/SCanvas/index.vue')['default']
    SCharacter: typeof import('./lib/components/SCharacter/index.vue')['default']
    SGLTF: typeof import('./lib/components/SGLTF/index.vue')['default']
    SUI: typeof import('./lib/components/SUI/index.vue')['default']
  }
}
